Repository team-brick-organization/Front, pull requests merged in 2024-07, with the labels that each got.

#1 KAN-3-chore: 프로젝트 세팅
  .eslintrc.json
  .github/pull_request_template.md
  .github/workflows/cypress.yml
  .husky/pre-commit
  .nvmrc
  .prettierrc
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components.json
  cypress.config.ts
  cypress/e2e/test.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/next.svg
  public/vercel.svg
  tailwind.config.ts
Labels: 잡일

#2 KAN-3-chore: 프로젝트 세팅 (#1)
  .eslintrc.json
  .github/pull_request_template.md
  .github/workflows/cypress.yml
  .husky/pre-commit
  .nvmrc
  .prettierrc
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components.json
  cypress.config.ts
  cypress/e2e/test.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/next.svg
  public/vercel.svg
  tailwind.config.ts
Labels: 잡일

#3 KAN-5-chore: tailwind config 세팅
  tailwind.config.ts
Labels: 잡일

#4 KAN-15-chore: radix 설치
  apis/.gitkeep
  app/layout.tsx
  constants/.gitkeep
  hooks/.gitkeep
  package-lock.json
  package.json
  styles/globals.css
  utils/.gitkeep
Labels: 잡일

#5 KAN-6-feat: Input 컴포넌트 제작
  components/Input.tsx
Labels: 기능 구현

#6 KAN-10-feat: Tab 컴포넌트 구현
  components/Tab.tsx
  hooks/.gitkeep
  hooks/useTab.ts
Labels: 기능 구현

#7 KAN-12-feat: NestingAvatar 컴포넌트 구현
  components/NestingAvatar.tsx
Labels: 기능 구현

#9 KAN-8-feat : Gnb 컴포넌트 초안
  components/Gnb.tsx
Labels: 기능 구현

#10 KAN-11-feat : PeopleCounter (인원수프로그레스바)초안, Radix UI Progress install
  components/AnimatedProgress.tsx
  components/PeopleCounter.tsx
  package-lock.json
  package.json
Labels: 기능 구현

#12 KAN-7-feat: react hook form 사용 로그인, 회원가입 폼 제작
  components/Input.tsx
  components/SignInForm.tsx
  components/SignUpForm.tsx
  constants/RegExr.ts
  package-lock.json
  package.json
Labels: 기능 구현

#15 BRICK-28-feat: pretendard 폰트적용
  app/layout.tsx
  public/fonts/Pretendard/PretendardVariable.woff2
  styles/globals.css
Labels: 잡일

#16 BRICK-29-chore: tailwind config에 커스텀 폰트 지정
  tailwind.config.ts
Labels: 잡일

#13 BRICK-19-feat: 디자인 변경, 함수 설명 주석 추가
  components/AnimatedProgress.tsx
  components/PeopleCounter.tsx
Labels: 기능 구현

#14 BRICK-18-refactor: 찜 버튼 컴포넌트 수정
  components/FavoriteButton.tsx
  public/images/svgs/heart.svg
  public/images/svgs/heartBlack.svg
  public/images/svgs/starGray.svg
  public/images/svgs/starYellow.svg
Labels: 리팩토링

#17 BRICK-20-feat: 탭 컴포넌트 수정
  .eslintrc.json
  components/Tab.tsx
  components/index.ts
  hooks/useTab.ts
  package-lock.json
  package.json
  postcss.config.mjs
  styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: 잡일, 기능 구현

#18 BRICK-16-feat: GNB 와이어프레임 기반 초안 수정
  .eslintrc.json
  components/Gnb.tsx
  components/Gnb/Gnb.tsx
  components/Gnb/Search.tsx
  store/useSearchStore.ts
Labels: 기능 구현

#19 BRICK-17-feat: 로그인, 회원가입 컴포넌트 제작(디자인완성 및 API들어가는 기능 제외 완성
  app/signin/page.tsx
  app/signup/email/page.tsx
  app/signup/page.tsx
  components/Input.tsx
  components/SignInForm.tsx
  components/SignUpEmail.tsx
  components/SignUpForm.tsx
  components/SignUpStart.tsx
  constants/RegExr.ts
  hooks/usePasswordVisibility.ts
  public/images/svgs/kakaoTalk.svg
  public/images/svgs/visibility.svg
  public/images/svgs/visibilityOff.svg
Labels: 기능 구현, 리팩토링

#20 BRICK-49-chore: 전반적인 수정
  components/Gnb/Gnb.tsx
  components/Gnb/Search.tsx
  components/Input.tsx
  components/PeopleCounter/AnimatedProgress.tsx
  components/PeopleCounter/PeopleCounter.tsx
  components/SignUpEmail.tsx
  components/index.ts
  constants/.gitkeep
  stores/useSearchStore.ts
  tsconfig.json
Labels: 잡일

#21 BRICK-50-chore: import 문제 수정
  components/Gnb/Gnb.tsx
  components/Gnb/Search.tsx
  components/Gnb/index.ts
  components/PeopleCounter/AnimatedProgress.tsx
  components/PeopleCounter/PeopleCounter.tsx
  components/PeopleCounter/index.ts
  components/SignInForm.tsx
  components/Tab.tsx
Labels: 잡일

#22 BRICK-52-chore: index import 문제 수정
  components/Gnb/Gnb.tsx
  components/Gnb/Search.tsx
  components/Gnb/index.ts
  components/PeopleCounter/PeopleCounter.tsx
  components/PeopleCounter/index.ts
Labels: 잡일

#24 BRICK-25-feat: 크루 모임 정보 컴포넌트 구현
  .eslintrc.json
  components/CrewGatheringInfo/CrewGatheringInfo.tsx
  components/CrewGatheringInfo/IconLabel.tsx
  components/FavoriteButton.tsx
  components/Gnb/Gnb.tsx
  components/NestingAvatar.tsx
  components/ParticipantsInfo.tsx
  components/PeopleCounter/PeopleCounter.tsx
  components/TagBadge/TagBadge.tsx
  components/TagBadge/TagBadgeList.tsx
  components/index.ts
  public/images/svgs/calendar.svg
  public/images/svgs/card.svg
  public/images/svgs/check.svg
  public/images/svgs/location.svg
  tsconfig.json
  utils/formatDate.ts
Labels: 기능 구현

#23 BRICK-32-feat: 등록하기_크루, 소셜 선택 컴포넌트 제작
  app/layout.tsx
  components/CardRegistration.tsx
  components/CrewReviewWriteModal.tsx
  components/Portal.tsx
  components/index.ts
  hooks/usePortal.ts
Labels: 잡일, 기능 구현

#25 Feature/BRICK-53: 비밀번호 찾기 페이지 구현
  app/password-find/page.tsx
  components/Input.tsx
  components/PasswordFindForm.tsx
  components/index.ts
Labels: 잡일, 기능 구현

#26 BRICK-30-feat: 소셜카드 제작, 테일윈드 추가된 폰트 설정
  components/GatheringCard.tsx
  components/index.ts
  tailwind.config.ts
Labels: 잡일, 기능 구현

#28 BRICK-22-feat: 카드리스트 컴포넌트, 카드분류 훅 추가
  components/CardList.tsx
  components/index.ts
Labels: 기능 구현

#32 BRICK-24-feat: 이미지 뷰어 모달창 구현, api연동x=>목데이터로
  app/page.tsx
  components/ImageViewer/ImageViewer.tsx
  components/ImageViewer/ImageViewerModal.tsx
  components/Portal.tsx
  components/index.ts
  next.config.mjs
  public/images/svgs/chevronleft.svg
  public/images/svgs/chevronright.svg
  public/images/svgs/close.svg
  public/images/svgs/viewMoreImage.svg
Labels: 잡일, 기능 구현, 미완성

#29 BRICK-56-feat: 카테고리 태그 리스트 구현
  components/CategoryTag/CategoryTag.tsx
  components/CategoryTag/CategoryTagList.tsx
  components/index.ts
Labels: 잡일, 기능 구현

#30 BRICK-45-feat: 소셜 소개 컴포넌트 구현
  app/layout.tsx
  components/CustomBadge/CustomBadge.tsx
  components/CustomBadge/TagBadgeList.tsx
  components/GatheringCard.tsx
  components/KakaoMap.tsx
  components/LocationMap.tsx
  components/Participants.tsx
  components/ParticipantsList.tsx
  components/SocialDescription.tsx
  components/SocialIntroduce.tsx
  components/Tab.tsx
  components/TagBadge/TagBadge.tsx
  components/index.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: 기능 구현

#31 BRICK-54-fix: GNB 로그인 했을시 프로필 이미지 뜨게 변경, 로그인 정보 가져오는 훅 추가
  components/Gnb/Gnb.tsx
  hooks/useGetProfileImg.ts
Labels: 기능 구현

#34 BRICK-34-feat: 소셜 등록 폼 컴포넌트 구현
  app/(auth)/layout.tsx
  app/(auth)/password-find/page.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/email/page.tsx
  app/(auth)/signup/page.tsx
  app/layout.tsx
  app/page.tsx
  app/signin/page.tsx
  app/signup/email/page.tsx
  app/signup/page.tsx
  components.json
  components/CrewGatheringInfo/CrewGatheringInfo.tsx
  components/Input.tsx
  components/PasswordFindForm.tsx
  components/SignInForm.tsx
  components/SignUpEmail.tsx
  components/SignUpEmailForm.tsx
  components/SignUpStart.tsx
  components/SignUpStartForm.tsx
  components/SocialDateTime.tsx
  components/SocialDateTimeButton.tsx
  components/SocialRegistrationForm.tsx
  components/UploadImages/UploadImageCard.tsx
  components/UploadImages/UploadImageCardsList.tsx
  components/UploadImages/UploadImages.tsx
  components/index.ts
  hooks/useDate.tsx
  hooks/useImageFiles.ts
  package-lock.json
  package.json
  public/images/svgs/arrowLeft.svg
  public/images/svgs/arrowRight.svg
  public/images/svgs/crossSmall.svg
  public/images/svgs/image.svg
  public/images/svgs/kakaoTalk.svg
  public/images/svgs/visibility.svg
  public/images/svgs/visibilityOff.svg
  styles/SocialDateTimePicker.css
  styles/globals.css
  tailwind.config.ts
  tsconfig.json
  types/global.d.ts
  utils/filterPassedTime.ts
  utils/openPostCodeSearch.ts
  utils/validateAndAdjustInputNumber.ts
Labels: 잡일, 기능 구현, 리팩토링

#35 BRICK-31-feat: 하단 참여/가입 컴포넌트 구현
  app/page.tsx
  components/BottomBar.tsx
  components/SocialRegistrationForm.tsx
  components/index.ts
  package-lock.json
  tailwind.config.ts
Labels: 잡일, 기능 구현

#39 BRICK-57-feat: 페이지네이션 컴포넌트 구현
  components/Pagination.tsx
  components/index.ts
Labels: 기능 구현

#41 BRICK-73-refactor: Tab 컴포넌트 컴파운드 컴포넌트 패턴으로 변경
  app/page.tsx
  components/Tab.tsx
  components/Tab/List.tsx
  components/Tab/MyPageTab.tsx
  components/Tab/Panel.tsx
  components/Tab/Provider.tsx
  components/Tab/SocialDetailPageTab.tsx
  components/Tab/Tab.tsx
  components/index.ts
  stores/createTabStore.ts
  tailwind.config.ts
Labels: 기능 구현, 리팩토링

#37 BRICK-72-feat: 포탈을 이용한 이미지 뷰어 모달창 반응형 구현 및 사이즈 조정
  components/ImageViewer/ImageViewer.tsx
  components/ImageViewer/ImageViewerModal.tsx
  components/ImageViewer/mockImages.ts
  public/images/svgs/chevronleft.svg
  public/images/svgs/chevronright.svg
  public/images/svgs/moreImg.svg
Labels: 잡일, 기능 구현

#40 BRICK-67-feat: 로그인,회원가입 반응형
  app/(auth)/layout.tsx
  app/(auth)/password-find/page.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/email/page.tsx
  app/(auth)/signup/page.tsx
  app/layout.tsx
  components/PasswordFindForm.tsx
  components/ProfileImageChangeModal.tsx
  components/SignInForm.tsx
  components/SignUpEmailForm.tsx
  components/SignUpStartForm.tsx
  hooks/useWindowWidth.ts
  moreImg.svg
Labels: 기능 구현

#38 BRICK-70-feat: 카드에 찜버튼 추가 및 기능 적용, 뱃지,카드,카드리스트 반응형 추가
  components/CardList.tsx
  components/CustomBadge/CustomBadge.tsx
  components/FavoriteButton.tsx
  components/GatheringCard.tsx
  public/images/svgs/heart.svg
  public/images/svgs/heartBlack.svg
  public/images/svgs/location.svg
Labels: 기능 구현

#42 BRICK-63-feat: 마이페이지 소셜카드 컴포넌트,카드 리스트 제작, 타입 재지정, 짜잘한 css 수정
  components/CardList.tsx
  components/CrewGatheringInfo/CrewGatheringInfo.tsx
  components/CustomBadge/CustomBadge.tsx
  components/CustomBadge/TagBadgeList.tsx
  components/GatheringCard.tsx
  components/MypageCards/MypageCard.tsx
  components/MypageCards/MypageCardList.tsx
  components/NestingAvatar.tsx
  components/ParticipantsInfo.tsx
  components/PeopleCounter/PeopleCounter.tsx
  components/index.ts
  hooks/useFavorite.ts
Labels: 기능 구현, 리팩토링

#43 BRICK-43-feature: 소셜 등록 페이지
  app/page.tsx
  app/registration/layout.tsx
  app/registration/page.tsx
  app/registration/social/page.tsx
  components/BottomBar.tsx
  components/CategoryTag/CategoryTag.tsx
  components/CategoryTag/CategoryTagList.tsx
  components/Gnb/Gnb.tsx
  components/ImageViewer/ImageViewerModal.tsx
  components/SocialDateTime.tsx
  components/SocialDateTimeButton.tsx
  components/SocialRegistrationForm.tsx
  components/UploadImages/UploadImages.tsx
  constants/categories.ts
  hooks/useDate.tsx
  hooks/useImageFiles.ts
  public/images/svgs/infoCircle.svg
  stores/useSocialRegistrationStore.ts
  styles/SocialDateTimePicker.css
Labels: 기능 구현

#46 BRICK-66-feat: 리액트 훅폼 이용 마이페이지 프로필 수정 기능 + 정보 변경 기능(api 미적용) + 반응형
  app/mypage/edit-profile/page.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  app/page.tsx
  components/ManagingMyInfo.tsx
  components/ProfileImageChangeModal.tsx
  components/index.ts
  constants/RegExr.ts
  package-lock.json
  package.json
  public/images/svgs/close.svg
  public/images/svgs/goback.svg
  public/images/svgs/pencil.svg
  stores/useProfileImageStore.ts
Labels: 잡일, 기능 구현

#47 BRICK-74-feat: 패스워드 리셋 컴포넌트, 토스트 메시지, EmailJs 인증 메일 구현
  app/layout.tsx
  components/PasswordResetVerifier.tsx
  components/ToastMessageTrigger.tsx
  components/index.ts
  package-lock.json
  package.json
  styles/globals.css
  utils/sendVerificationEmail.ts
Labels: 기능 구현

#45 BRICK-61-feat: 마이페이지 프로필 컴포넌트 구현
  components/CustomBadge/CustomBadge.tsx
  components/ProfileCard.tsx
  components/index.ts
Labels: 기능 구현

#48 BRICK-71-feat: 소셜 qna 컴포넌트 구현
  app/page.tsx
  components/DotsDropDownMenu.tsx
  components/Gnb/Search.tsx
  components/KakaoMap.tsx
  components/LocationMap.tsx
  components/Pagination.tsx
  components/ParticipantsList.tsx
  components/QnaDetailModal.tsx
  components/QnaWriteModal.tsx
  components/SignInForm.tsx
  components/SignUpStartForm.tsx
  components/SocialQna.tsx
  components/SocialQnaCard.tsx
  components/SocialQnaCardList.tsx
  components/Tab/MyPageTab.tsx
  components/Tab/Provider.tsx
  components/Tab/SocialDetailPageTab.tsx
  components/index.ts
  hooks/useWindowWidth.ts
  public/images/svgs/chevronleft.tsx
  public/images/svgs/chevronright.tsx
  public/images/svgs/mapMarker.svg
  public/images/svgs/pen.svg
  utils/shortFormatDate.ts
Labels: 기능 구현

#49 BRICK-58-feat: 공용 Button Component 구현
  components/Button.tsx
  package-lock.json
  package.json
Labels: 기능 구현

#50 BRICK-65-feat: 검색 페이지에서 사용을 위한 Search 컴포넌트 수정, sidemenu 적용, 로그인 프롭 내려주는거 수정 및 자잘한 수정
  components/Gnb/Gnb.tsx
  components/Gnb/Search.tsx
  components/Gnb/Sidemenu.tsx
  components/index.ts
  public/images/svgs/logo.svg
  stores/useUserStore.ts
Labels: 기능 구현

#51 BRICK-81-feat: 추가 이미지 아이콘 및 숫자삭제
  app/page.tsx
  components/ImageViewer/ImageViewer.tsx
  components/ImageViewer/mockImages.ts
Labels: 리팩토링

#52 BRICK-68-feat: 모임정보 컴포넌트 반응형 구현 & 카카오 공유 기능 추가
  app/layout.tsx
  app/page.tsx
  components/Button.tsx
  components/FavoriteButton.tsx
  components/GatheringInfo/GatheringInfo.tsx
  components/GatheringInfo/IconLabel.tsx
  components/KakaoScript.tsx
  components/KakaoShareModal.tsx
  components/MypageCards/MypageCard.tsx
  components/NestingAvatar.tsx
  components/ParticipantsInfo.tsx
  components/PeopleCounter/PeopleCounter.tsx
  components/ProfileImageChangeModal.tsx
  components/ToastMessageTrigger.tsx
  components/index.ts
  public/images/svgs/calendar.svg
  public/images/svgs/card.svg
  public/images/svgs/kakaoTalkYellow.svg
  public/images/svgs/location.svg
  tailwind.config.ts
Labels: 기능 구현

#54 BRICK-55-feat: banner 추가(이미지 미적용)
  components/Banner.tsx
  package-lock.json
  package.json
Labels: 잡일, 기능 구현

#56 BRICK-78-feat: UploadImages 컴포넌트 대표이미지 기능 추가
  components/SocialRegistrationForm.tsx
  components/UploadImages/UploadImageCard.tsx
  components/UploadImages/UploadImageCardsList.tsx
  components/UploadImages/UploadImages.tsx
  hooks/useImageFiles.ts
Labels: 기능 구현

#57 BRICK-84-feat: 마이페이지 유저정보 수정 저장시 모달 띄우기 구현
  app/mypage/edit/profile/page.tsx
  components/Gnb/Gnb.tsx
  components/InfoPortal.tsx
  components/ManagingMyInfo.tsx
  components/ProfileImageChangeModal.tsx
  components/RegistrationSuccessUserInfoModal.tsx
  components/index.ts
  hooks/useUserInfoPortal.ts
  public/images/svgs/person.svg
Labels: 잡일, 기능 구현

#60 BRICK-79-feat: 소셜 등록 폼 인풋 크기 수정 & 글자수 제한
  components/DisplayMaxLength.tsx
  components/Input.tsx
  components/SocialRegistrationForm.tsx
  components/UploadImages/UploadImages.tsx
  components/index.ts
  styles/SocialDateTimePicker.css
Labels: 기능 구현, 에러

#58 BRICK-83-fix: 비밀번호 변경 컴포넌트 버튼 및 문구 수정, 이메일 보내는 함수에 재전송인지 내려주는 프롭 추가
  app/layout.tsx
  components/PasswordResetVerifier.tsx
  components/ToastMessageTrigger.tsx
  styles/globals.css
  utils/sendVerificationEmail.ts
Labels: 기능 구현

#62 BRICK-80-feat: 소셜 qna 등록, qna 댓글 인풋 글자수 제한
  app/page.tsx
  components/QnaDetailModal.tsx
  components/QnaWriteModal.tsx
Labels: 기능 구현

#64 BRICK-92-feat: 모임 수정하기 컴포넌트 구현
  app/layout.tsx
  app/socials/[id]/edit/page.tsx
  components/QnaWriteModal.tsx
  components/SocialDateTime.tsx
  components/SocialRegistrationForm.tsx
  hooks/useDate.tsx
  hooks/useImageFiles.ts
Labels: 기능 구현

#67 BRICK-89-feat: 중복처리,redirect,사이드메뉴, 반응형, 드롭다운등 구현
  apis/postDuplicateCheck.ts
  apis/postDuplicateEmail.ts
  apis/postEditUserInfo.ts
  app/(Gnb)/mypage/edit/account/page.tsx
  app/(Gnb)/mypage/edit/layout.tsx
  app/(Gnb)/mypage/edit/profile/page.tsx
  app/(Gnb)/mypage/page.tsx
  app/layout.tsx
  components/ManagingMyInfo.tsx
  components/MyInfoSideMenu.tsx
  components/ProfileImageChangeModal.tsx
  components/SignUpEmailForm.tsx
  components/index.ts
  constants/RegExr.ts
  public/images/svgs/dropdown.svg
  stores/useEditProfileImageStore.ts
  stores/useProfileImageStore.ts
  types/postDuplicateEmail.d.ts
  types/types.ts
Labels: 잡일, 기능 구현

#68 BRICK-40-feat: 소셜 상세 페이지 구현 & 자잘한 수정
  app/(Gnb)/page.tsx
  app/(Gnb)/registration/page.tsx
  app/(Gnb)/socials/[id]/page.tsx
  components/BottomBar.tsx
  components/GatheringInfo/GatheringInfo.tsx
  components/Gnb/Gnb.tsx
  components/Gnb/Sidemenu.tsx
  components/ImageViewer/ImageViewer.tsx
  components/KakaoMap.tsx
  components/NestingAvatar.tsx
  components/Pagination.tsx
  components/ParticipantsList.tsx
  components/Portal.tsx
  components/Tab/SocialDetailPageTab.tsx
  public/images/svgs/chevronleft.tsx
  public/images/svgs/chevronright.tsx
  tailwind.config.ts
  utils/getEventStatus.ts
Labels: 기능 구현, 리팩토링

#70 BRICK-99-feat: 마이페이지 계정설정 위치 조정
  app/(Gnb)/mypage/edit/account/page.tsx
  components/PasswordResetVerifier.tsx
Labels: 잡일

#72 BRICK-101-feat: 내 정보 관리 페이지 dropdown 수정
  app/(Gnb)/mypage/edit/profile/page.tsx
  components/MyInfoSideMenu.tsx
Labels: 잡일

#74 BRICK-102-feat: 계정설정 dropdown 제작
  app/(Gnb)/mypage/edit/account/page.tsx
  components/PasswordResetVerifier.tsx
  public/images/svgs/checkedGray10.svg
Labels: 기능 구현

#75 BRICK-95-feat: 모집중, 모집마감, 찜한모임 페이지 구현 & 사소한 수정
  app/(Gnb)/layout.tsx
  app/(Gnb)/liked/layout.tsx
  app/(Gnb)/liked/page.tsx
  app/(Gnb)/socials/[id]/page.tsx
  app/(Gnb)/socials/layout.tsx
  app/(Gnb)/socials/page.tsx
  app/(noGnb)/search/[id]/page.tsx
  components/FavoriteButton.tsx
  components/GatheringCards/GatheringCard.tsx
  components/GatheringCards/GatheringCardList.tsx
  components/Gnb/Gnb.tsx
  components/Gnb/Sidemenu.tsx
  components/SortButtons.tsx
  components/Tab/SocialDetailPageTab.tsx
  components/index.ts
  public/images/pngs/calendar.png
  public/images/pngs/hands.png
  public/images/pngs/pin.png
  public/images/svgs/doodle.svg
  public/images/svgs/location.svg
  tailwind.config.ts
  utils/getEventStatus.ts
Labels: 기능 구현, 리팩토링

#78 BRICK-105-feat: 닉네임 중복검사 로직 도입
  apis/postDuplicateCheck.ts
  apis/postEditUserInfo.ts
  components/ManagingMyInfo.tsx
  components/SignInForm.tsx
  components/SignUpEmailForm.tsx
  constants/RegExr.ts
  public/images/svgs/checked.svg
  public/images/svgs/unChecked.svg
  types/postDuplicateEmail.d.ts
  types/types.ts
Labels: 잡일, 기능 구현
