Repository team-brick-organization/Front, pull requests merged in 2024-08, with the labels that each got.

#79 BRICK-112-feat: 피그마 디자인 수정사항 반영, defaultValue 적용
  apis/getUser.ts
  apis/postEditProfile.ts
  apis/postSignUp.ts
  components/Gnb/Gnb.tsx
  components/Gnb/Sidemenu.tsx
  components/ManagingMyInfo.tsx
  components/MyInfoSideMenu.tsx
  components/ProfileCard.tsx
  components/ProfileImageChangeModal.tsx
  components/SignInForm.tsx
  components/SignUpEmailForm.tsx
  components/SocialDetailsImgCarouselProps.tsx
Labels: 기능 구현, 에러

#83 BRICK-115-feat: 내 정보 관리 redirect 문제 해결
  components/ManagingMyInfo.tsx
Labels: 에러

#84 BRICK-116-feat: 회원탈퇴 구현 + 마이페이지 완성
  apis/deleteUserAccount.ts
  apis/getUserImage.ts
  apis/patchEditUserInfo.ts
  app/(Gnb)/mypage/edit/account/page.tsx
  app/(Gnb)/mypage/edit/layout.tsx
  components/Gnb/Gnb.tsx
  components/ManagingMyInfo.tsx
  components/PasswordResetVerifier.tsx
  components/ProfileImageChangeModal.tsx
  public/images/svgs/checkedCheckBox.svg
  public/images/svgs/unCheckedCheckBox.svg
  stores/useUserDataStore.tsx
  stores/useUserStore.ts
Labels: 잡일, 기능 구현

#87 BRICK-120-refactor: 이미지 최적화
  app/(Gnb)/page.tsx
  components/MainPage.tsx
  components/index.ts
  next.config.mjs
  package-lock.json
  package.json
  public/images/avifs/banner.avif
  public/images/avifs/bannerBlur.avif
Labels: 리팩토링

#91 BRICK-123-feat: 검색페이지 api 연결 & 기타 디테일 수정
  apis/getSocials.ts
  apis/patchEditComment.ts
  app/(Gnb)/socials/[id]/page.tsx
  app/(Gnb)/socials/page.tsx
  app/(noGnb)/search/[id]/page.tsx
  app/(noGnb)/search/layout.tsx
  app/(noGnb)/search/page.tsx
  components/CommentEditForm.tsx
  components/CustomBadge/CustomBadge.tsx
  components/DisplayMaxLength.tsx
  components/FavoriteButton.tsx
  components/GatheringCards/GatheringCard.tsx
  components/GatheringInfo/GatheringInfo.tsx
  components/Gnb/Search.tsx
  components/MainPage.tsx
  components/MainPageTopButtonGroup.tsx
  components/ManagingMyInfo.tsx
  components/ProfileImageChangeModal.tsx
  components/QnaDetailModal.tsx
  components/SocialDateTime.tsx
  components/SocialDetailsImgCarouselProps.tsx
  components/SocialQna.tsx
  components/SocialRegistrationForm/SocialIntroduceSection.tsx
  components/SocialRegistrationForm/SocialNameSection.tsx
  hooks/useImageFiles.ts
  public/images/svgs/heartOutlineFill.svg
  public/images/svgs/main_socialsButton.svg
  stores/useSocialDetailStore.ts
  styles/SocialDateTimePicker.css
  types/getSocialDetails.d.ts
  types/getSocials.d.ts
  utils/getEventStatus.ts
Labels: 기능 구현, 리팩토링

#94 BRICK-126-refactor: 모임 상세 모임 마감시 조건 처리 & 마이페이지 카드 반응형 수정
  app/(Gnb)/mypage/page.tsx
  components/GatheringInfo/GatheringInfo.tsx
  components/Gnb/Gnb.tsx
  components/MypageCards/MypageCard.tsx
  components/MypageCards/MypageCardList.tsx
  components/ProfileCard.tsx
  tailwind.config.ts
Labels: 기능 구현, 리팩토링

#95 BRICK-127-refactor: 메인 페이지 디자인 수정 & gnb 찜한 쇼설 => 찜한 모임으로 수정
  components/Gnb/Gnb.tsx
  components/MainPage.tsx
  public/images/avifs/banner.avif
  public/images/svgs/banner.svg
Labels: 기능 구현, 리팩토링
